# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Corona Infos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'

  # Pods for Corona Infos

  target 'Corona InfosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Corona InfosUITests' do
    # Pods for testing
  end

end
